"""
FARSIX Llama Fast Agent
Model: meta/llama-3.1-8b-instruct (NVIDIA hosted)
Role: Fast summarization and structured executive report generation.
      Takes Nemotron reasoning chain → clean markdown report.

Output: Formatted executive summary report (markdown string).
"""

import asyncio
import time
from typing import Any, Dict, Optional

from backend.event_bus import Event, get_event_bus
from backend.nim_router import NIMRouter


SYSTEM_PROMPT = """You are LLAMA — the Fast Reporting Agent for FARSIX Physical AI systems.

You receive a detailed reasoning chain from the Nemotron Analysis Agent and a physical
scene summary from the Nemotron Vision Agent. Your job is to produce a CLEAN, PROFESSIONAL,
ACTIONABLE executive intelligence report.

The report MUST follow this exact structure:

# 🔍 FARSIX Intelligence Report

## Executive Summary
[2-3 sentence high-level overview — suitable for a non-technical executive]

## Situation Assessment
[Clear description of the current situation and its severity]

## Key Findings
[Bullet list of the most critical findings, ranked by severity]

## Risk Matrix
| Risk | Severity | Probability | Impact | Timeframe |
|------|----------|-------------|--------|-----------|
[Fill in 3-6 rows]

## Priority Actions
### 🔴 Immediate (< 24 hours)
[Specific actions that must happen NOW]

### 🟡 Short-term (< 7 days)
[Actions needed this week]

### 🟢 Long-term (< 30 days)
[Planned improvements]

## Resource Requirements
[Personnel, equipment, and cost estimates]

## Confidence Assessment
[Confidence level in recommendations and what additional data would improve it]

## Conclusion
[One clear closing statement]

---
*Report generated by FARSIX Multi-Agent Intelligence System*
*Agents: Nemotron Vision | Nemotron Reasoning | NeMo Guardrails | Llama Fast*

Keep the report professional, specific, and directly actionable. Avoid vague language."""


class LlamaAgent:
    """
    Llama Fast Agent — calls meta/llama-3.1-8b-instruct via NVIDIA NIM.

    Usage:
        agent = LlamaAgent(router)
        report = await agent.run(
            reasoning_chain="...",
            vision_summary={...},
            mission_id="m-001"
        )
    """

    AGENT_NAME = "llama_agent"
    DISPLAY_NAME = "LLAMA"
    COLOR = "#A5D6A7"  # Green

    def __init__(self, router: NIMRouter):
        self.router = router
        self.bus = get_event_bus()
        self.decision = router.route("summarize")
        self.model = self.decision.model_id

    # ------------------------------------------------------------------ #
    #  Main entry point                                                     #
    # ------------------------------------------------------------------ #

    async def run(
        self,
        reasoning_chain: str,
        vision_summary: Optional[Dict[str, Any]] = None,
        mission_id: str = "unknown",
    ) -> str:
        """
        Generate executive report from Nemotron reasoning.

        Args:
            reasoning_chain: Full markdown reasoning from NemotronAgent.
            vision_summary:  Optional Nemotron Vision scene summary for grounding.
            mission_id:      For event bus tagging.

        Returns:
            Formatted markdown report string.
        """
        t_start = time.time()
        self._publish("agent_started", mission_id, {
            "message": "🔵 LLAMA generating executive intelligence report...",
        })
        self._publish("routing", mission_id, {"message": self.decision.log_line})

        user_content = self._build_user_message(reasoning_chain, vision_summary)

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                self._call_nim,
                user_content,
            )

            elapsed = round(time.time() - t_start, 2)
            word_count = len(response.split())

            self._publish("agent_complete", mission_id, {
                "message": (
                    f"✅ LLAMA report generated in {elapsed}s | "
                    f"{word_count} words"
                ),
                "elapsed": elapsed,
                "tokens_used": len(user_content.split()) + word_count,
                "report_preview": response[:200] + "..." if len(response) > 200 else response,
            })

            return response

        except Exception as exc:
            self._publish("agent_error", mission_id, {
                "message": f"❌ LLAMA ERROR: {exc}",
                "error": str(exc),
            })
            raise

    # ------------------------------------------------------------------ #
    #  NIM API call (sync — run in executor)                                #
    # ------------------------------------------------------------------ #

    def _call_nim(self, user_content: str) -> str:
        client = self.router.get_client()
        response = client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
            temperature=0.4,
            max_tokens=2048,
            top_p=0.9,
        )
        return response.choices[0].message.content or ""

    # ------------------------------------------------------------------ #
    #  Helpers                                                              #
    # ------------------------------------------------------------------ #

    def _build_user_message(
        self,
        reasoning_chain: str,
        vision_summary: Optional[Dict[str, Any]],
    ) -> str:
        parts = []

        if vision_summary:
            scene_summary = vision_summary.get("scene_summary", "")
            risk_score = vision_summary.get("overall_risk_score", "N/A")
            immediate = vision_summary.get("immediate_action_required", False)
            parts.append(
                f"## Physical Scene Context (from Nemotron Vision)\n"
                f"- **Scene**: {scene_summary}\n"
                f"- **Overall Risk Score**: {risk_score}/100\n"
                f"- **Immediate Action Required**: {'YES ⚠️' if immediate else 'No'}\n\n"
            )

        parts.append(
            f"## Nemotron Reasoning Chain\n"
            f"{reasoning_chain}\n\n"
            f"## Your Task\n"
            f"Synthesise all of the above into a clean, professional, "
            f"executive intelligence report following your system prompt format exactly. "
            f"Be specific. Avoid padding. Make every sentence count."
        )

        return "\n".join(parts)

    def _publish(self, event_type: str, mission_id: str, data: dict) -> None:
        self.bus.publish(Event(
            event_type=event_type,
            source=self.AGENT_NAME,
            mission_id=mission_id,
            data=data,
        ))
